name: CI

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci_build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, window-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build


  ci_eslint:
    name: eslint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: ./src




  ci_prettier:
    name: prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
        run: npm ci
      - name: Format check
        run: npm run format
    

    