name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci_build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        od: [ubuntu-latest]
        # os: [ubuntu-latest, window-latest]
        node-version: [ latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node in ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build

  ci_eslint_prettier:
    name: eslint & prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm ci
      - name: ESLint
        run: npm run lint
      - name: prettier
        run: npm run format
